### ISSUE TITLE
createissue: support additional fields

### ISSUE THREAD

**Issue by zenogantner** [trentm/jirash#15]
When trying to create an issue with our JIRA, I get the following error:

Traceback (most recent call last):
...
Fault: <Fault 0: 'java.lang.Exception: com.atlassian.jira.rpc.exception.RemoteValidationException: {customfield_10620=QA status is required.} : []'>

It would be nice if one could specify values for arbitrary fields, e.g.
-f "QA status: Test case exists"

**Comment by trentm** [comment]
I think like the feature idea, but (a) this is really old now and (b) I won't have time to implement this myself, so I'm closing this. If someone is willing, then I'd look at a PR.
