### ISSUE TITLE
Get Description of a Ticket 

### ISSUE THREAD

**Issue by ubersol** [trentm/jirash#19]
This is not a bug but a feature request:

When you do:

[drende@lem ~]$ jirash issue MYPROJ-81
MYPROJ-81: This is a test ticket (deniz -> john doe, Elevated, Open)

which is fine, but could we also get the description of the same ticket? That would be the first comments made when opening tickets.

**Comment by trentm** [comment]
Fair enough. PR and/or proposal are welcome. I won't have time to impl this myself.
