### ISSUE TITLE
update_filter bug

### ISSUE THREAD

**Issue by vtrevor** [trentm/jirash#33]
![Annotation 2020-04-02 142741](https://user-images.githubusercontent.com/63263588/78603754-8769fe80-780d-11ea-80f9-f9bceef8c498.png)

Issue after creating a filter, if the description is 'None' or is blank, when you go to update the filter it will break. Located on line 956 I believe, it does not allow for a pass through of 'None' into the update filter. Work around is currently to have the same description for both and not leaving it blank.

**Comment by trentm** [comment]
@vtrevor Did you get this *recently* using jirash *v2*?  jirash v2 (first released 2017-11-10) was re-written in node.js.

In fact, AFAICT my repo has never *had* a "create_filter" function. Is this from some fork of jirash?
