### ISSUE TITLE
Support having JIRA behind HTTP Authentication

### ISSUE THREAD

**Issue by jacques** [trentm/jirash#4]
Can you add support for authenticating to a JIRA instance behind HTTP auth and support for username/password matching the jira credentials vs other credentials.

**Comment by asfaltboy** [comment]
@jacques Do you mean your instance has http auth in addition to Jira auth? If so, I believe you can simply add your creds in the url setting; for example: `http://user:password@jira.example.com`

**Comment by trentm** [comment]
jirash v2 (first released 2017-11-10) was re-written in node.js. This issue is for jirash v1, which is no longer supported so I'm closing this as "won't fix".
